config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  get "users/new"
  root "view_web#home"

  get "/admin", to: "view_admin#home"
  get "view_web/home", to: "view_web#home"
  get "view_web/about", to: "view_web#about"
  get "view_web/contacts", to: "view_web#contacts"
  get "view_web/product", to: "view_web#product"
  get "view_web/collections", to: "view_web#collections"
  get "view_web/account/register", to: "users#new"
  post "view_web/account/register",  to: "users#create"
  get "view_web/account", to: "view_web#account"
  get "view_web/cart", to: "view_web#cart"
  get "view_web/account/login", to: "sessions#new"
  post "view_web/account/login",  to: "sessions#create"
  delete "view_web/account/logout",  to: "sessions#destroy"
  resources :users


  resources :categories
  resources :small_categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :small_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  has_many :order_details
end

app/models/image_product.rb
class ImageProduct < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
  enum status: { put: 0, wait: 1, approved: 2, sent: 3 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :history
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :small_category
  has_many :image_products
  enum status: { stocking: 0, outofstock: 1 }
end

app/models/rank.rb
class Rank < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/slide.rb
class Slide < ApplicationRecord
end

app/models/small_category.rb
class SmallCategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


  has_many :contacts
  has_many :ranks
  has_many :comments
  has_one :history
  has_many :orders
  enum role: { admin: 0, member: 1 }

  has_secure_password

  validates :address, presence: true,
    length: {maximum: Settings.user.address_max_length}
  validates :email, presence: true, length: {maximum: Settings.user.email_length},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :name, presence: true, length: {maximum: Settings.user.name_length}
  validates :password, presence: true,
    length: {minimum: Settings.user.pass_length}, allow_nil: true
  validates :phone, presence: true,
    length: {maximum: Settings.user.phone_number_length}

  before_save ->{email.downcase!}

  def self.digest string
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = t "errors.msg1"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/small_categories_controller.rb
class SmallCategoriesController < ApplicationController
  before_action :load_small_category, except: [:new, :index, :create]
  def index
  	@small_categories = SmallCategory.all
  	@categories = Category.all
  end

  def new
  	@small_category = SmallCategory.new
  	@categories = Category.all
  end

  def edit
  	@categories = Category.all
  end

  def create
    @small_category = SmallCategory.new small_category_params
    if @small_category.save
      redirect_to small_categories_path
    else
      render :new
    end
  end

  def update
    if @small_category.update_attributes(small_category_params)
      flash[:success] = t "updated"
      redirect_to small_categories_path
    else
      render :edit
    end
  end

  def destroy
    if @small_category.destroy
      flash[:success] = t "small_category_deleted"
      redirect_to categories_path
    else
      flash[:danger] = t "small_category_not_found"
      redirect_to categories_path
    end
  end

  private

    def small_category_params
      params.require(:small_category).permit(:small_category_name, :description, :category_id)
    end

    def load_small_category
      @small_category = SmallCategory.find_by id: params[:id] 
      return if @small_category

      flash[:danger] = t "small_category_not_found"
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = t("welcome")
      redirect_to root_url
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :phone, :address,
       :password, :password_confirmation)
    end
end

app/controllers/view_web_controller.rb
class ViewWebController < ApplicationController
  def home
    @products = Product.joins("INNER JOIN ranks ON product_id = products.id").limit(12).order("star_level desc")
  end

  def about
  end

  def contacts
  end

  def product
  end

  def collections
  end

  def login
  end

  def account
  end

  def cart
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = I18n.t ".base_title"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in user
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete:user_id
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/view_admin_helper.rb
module ViewAdminHelper
end

app/helpers/view_web_helper.rb
module ViewWebHelper
end

app/views/small_categories/_form.html.erb
<%= form_for @small_category do |f| %>
  <input type="hidden" name="_token" value="{{ csrf_token() }}">
  <div class="box-body">
  	<div class="fields-group">
    	<div class="form-group  ">
    		<%= f.label :small_category_name, t(".namesmallcategory") %>
    		<%= f.text_field :small_category_name, class: "form-control" %>
    	</div>
    	<div class="form-group  ">
    		<%= f.label :description, t(".description") %>
		    <%= f.text_field :description, class: "form-control" %>
		  </div>

      <div class="form-group  ">
        <%= f.label :category_id, t(".namecategory") %>
        <select id="category" onchange="categoryChanged(this)">
          <% if @small_category.category_id? %>
            <option value=  <%= @small_category.category_id %> ><%= @small_category.category.name %></option>
             <% @categories.each do |category| %>
             <% if category.id != @small_category.category_id %>
            <option value=<%= category.id %> ><%= category.name %></option>
            <%end%>
          <%end%>
          

          <% else %>
            <option value="" >--Category--</option>
          <% @categories.each do |category| %>
          <option value=<%= category.id %> ><%= category.name %></option>
          <%end%>
          <%end%>
        </select>
         <%= f.hidden_field :category_id, id: :small_category_category_id %>
      </div>
    </div>
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
    <input type="hidden" name="_token" value="YkDCfkRWPRyZTW2zQVo3IfKy3x6paUJmuFe7BBwx">
    <div class="col-md-2"> </div>
    <div class="col-md-8">
      <div class="btn-group pull-right">
        <%= f.submit t(".submit"), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <input type="hidden" name="_previous_" value="" class="_previous_" />
  <!-- /.box-footer -->
<% end %>
 

<%= javascript_include_tag "small_category" %>

app/views/small_categories/edit.html.erb
<% provide(:title, t( ".title")) %>
  <div class="wrapper">
    <header class="main-header">
      <a href="/test/public/" class="logo">
        <span class="logo-mini"><b><%= t("adminHome.str1") %></b></span>
        <span class="logo-lg">
          <%= image_tag("Admin/img/scart-min.png", :alt => "img") %>
        </span>
      </a>
      <nav class="navbar navbar-static-top" role="navigation">
        <%=render "view_admin/elements/NavbarRightMenu" %>
      </nav>
    </header>
    <%=render "view_admin/elements/menu" %>
    <div class="content-wrapper" id="pjax-container">
      <section class="content-header">
        <h1><%= t ".str1" %></h1>
        <!-- breadcrumb start -->
        <!-- breadcrumb end -->
      </section>
      <section class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="box box-info">
              <div class="box-header with-border">
                <h3 class="box-title"><%= t ".str2" %></h3>
                <div class="box-tools">
                  <div class="btn-group pull-right" style="margin-right: 5px"> <a href= <%= categories_path %> class="btn btn-sm btn-default" title="List"><i class="fa fa-list"></i><span class="hidden-xs">&nbsp;<%= t ".list" %></span></a> </div>
                </div>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%=render "small_categories/form" %>
            </div>
          </div>
        </div>
      </section>
     <%= javascript_include_tag "edit" %>
    </div>
  </div>

app/views/small_categories/index.html.erb
<% provide(:title, t( ".title")) %>
  <div class="wrapper">
    <header class="main-header">
      <a href="/test/public/" class="logo">
        <span class="logo-mini"><b><%= t("adminHome.str1") %></b></span>
        <span class="logo-lg">
          <%= image_tag("Admin/img/scart-min.png", :alt => "img") %>
        </span>
      </a>
      <nav class="navbar navbar-static-top" role="navigation">
        <%=render "view_admin/elements/NavbarRightMenu" %>
      </nav>
    </header>
    <%=render "view_admin/elements/menu" %>
    <div class="content-wrapper" id="pjax-container">
      <section class="content-header">
        <h1><%= t ".str1"%></h1>
        <!-- breadcrumb start -->
        <!-- breadcrumb end -->
      </section>
      <section class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="box">
              <div class="box-header with-border">
                <div class="pull-right">
                  <div class="btn-group pull-right" style="margin-right: 10px">
                    <a href= <%= new_small_category_path %> class="btn btn-sm btn-success" title="New"> <i class="fa fa-save"></i><span class="hidden-xs">&nbsp;&nbsp;<%= t ".new" %></span> </a>
                  </div>
                </div> 
              </div>
              <!-- /.box-header -->
              <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th><%= t ".id" %></th>
                      <th><%= t ".namecategory" %></th>
                      <th><%= t ".description" %></th>
                      <th><%= t ".category" %></th>
                      <th><%= t ".action" %></th>
                    </tr>
                  </thead>
                  <tbody> 
                    <% @small_categories.each do |small_category| %>
                      <tr>
                        <td><%= small_category.id %></td>
                        <td><%= small_category.small_category_name %></td>
                        <td><%= small_category.description %></td>
                        <td><%= small_category.category.name %></td>                        
                        <td>
                          <a title="Show Customer detail" href= <%= edit_small_category_path(small_category) %> > 
                            <i class="fa fa-edit"></i> 
                          </a>
                          <a href= <%= small_category_path(small_category)%> data-method = "delete" data-confirm = "Bạn có chắc chắn xóa?" >  
                            <i class="fa fa-trash"> </i>                           
                          </a>
                        </td>
                      </tr> 
                    <% end %>
                  </tbody>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>

app/views/small_categories/new.html.erb
<% provide(:title, t( ".title")) %>
  <div class="wrapper">
    <header class="main-header">
      <a href="/test/public/" class="logo">
        <span class="logo-mini"><b><%= t("adminHome.str1") %></b></span>
        <span class="logo-lg">
          <%= image_tag("Admin/img/scart-min.png", :alt => "img") %>
        </span>
      </a>
      <nav class="navbar navbar-static-top" role="navigation">
        <%=render "view_admin/elements/NavbarRightMenu" %>
      </nav>
    </header>
    <%=render "view_admin/elements/menu" %>
    <div class="content-wrapper" id="pjax-container">
      <section class="content-header">
        <h1><%= t ".str1" %></h1>
        <!-- breadcrumb start -->
        <!-- breadcrumb end -->
      </section>
      <section class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="box box-info">
              <div class="box-header with-border">
                <h3 class="box-title"><%= t ".str2" %></h3>
                <div class="box-tools">
                  <div class="btn-group pull-right" style="margin-right: 5px"> <a href= <%= small_categories_path %> class="btn btn-sm btn-default" title="List"><i class="fa fa-list"></i><span class="hidden-xs">&nbsp;<%= t ".list" %></span></a> </div>
                </div>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%=render "small_categories/form" %>
            </div>
          </div>
        </div>
      </section>
      <%= javascript_include_tag "new" %>
    </div>
  </div>