config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  get "users/new"
  root "view_web#home"

  get "/admin", to: "view_admin#home"
  get "view_web/home", to: "view_web#home"
  get "view_web/about", to: "view_web#about"
  get "view_web/contacts", to: "view_web#contacts"
  get "view_web/product", to: "view_web#product"
  get "view_web/collections", to: "view_web#collections"
  get "view_web/account/register", to: "users#new"
  post "view_web/account/register",  to: "users#create"
  get "view_web/account", to: "view_web#account"
  get "view_web/cart", to: "view_web#cart"
  get "view_web/account/login", to: "sessions#new"
  post "view_web/account/login",  to: "sessions#create"
  delete "view_web/account/logout",  to: "sessions#destroy"
  resources :users


  resources :categories
  resources :small_categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :small_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  has_many :order_details
end

app/models/image_product.rb
class ImageProduct < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
  enum status: { put: 0, wait: 1, approved: 2, sent: 3 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :history
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :small_category
  has_many :image_products
  enum status: { stocking: 0, outofstock: 1 }
end

app/models/rank.rb
class Rank < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/slide.rb
class Slide < ApplicationRecord
end

app/models/small_category.rb
class SmallCategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


  has_many :contacts
  has_many :ranks
  has_many :comments
  has_one :history
  has_many :orders
  enum role: { admin: 0, member: 1 }

  has_secure_password

  validates :address, presence: true,
    length: {maximum: Settings.user.address_max_length}
  validates :email, presence: true, length: {maximum: Settings.user.email_length},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :name, presence: true, length: {maximum: Settings.user.name_length}
  validates :password, presence: true,
    length: {minimum: Settings.user.pass_length}, allow_nil: true
  validates :phone, presence: true,
    length: {maximum: Settings.user.phone_number_length}

  before_save ->{email.downcase!}

  def self.digest string
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = t "errors.msg1"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = t("welcome")
      redirect_to root_url
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :phone, :address,
       :password, :password_confirmation)
    end
end

app/controllers/view_admin_controller.rb
class ViewAdminController < ApplicationController
  def home
  end
  def index
  end
end

app/controllers/view_web_controller.rb
class ViewWebController < ApplicationController
  def home
    @products = Product.joins("INNER JOIN ranks ON product_id = products.id").limit(12).order("star_level desc")
  end

  def about
  end

  def contacts
  end

  def product
  end

  def collections
  end

  def login
  end

  def account
  end

  def cart
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = I18n.t ".base_title"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in user
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete:user_id
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/view_admin_helper.rb
module ViewAdminHelper
end

app/helpers/view_web_helper.rb
module ViewWebHelper
end

app/views/view_admin/elements/_NavbarRightMenu.html.erb
<div class="navbar-custom-menu">
  <ul class="nav navbar-nav">
    <!-- User Account Menu -->
    <li class="dropdown user user-menu">
      <!-- Menu Toggle Button -->
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <%=image_tag( "Admin/img/user2-160x160.jpg", :alt=> "User Image") %> <span class="hidden-xs"><%= t("adminMenu.str1") %></span> </a>
      <ul class="dropdown-menu">
        <!-- The user image in the menu -->
        <li class="user-header">
          <%=image_tag( "Admin/img/user2-160x160.jpg", :alt=> "User Image") %> </li>
        <li class="user-footer">
          <div class="pull-left">
            <a href="/admin/setting">
              <%=t ( "adminMenu.str10") %>
            </a>
          </div>
          <div class="pull-right">
            <a href="/amdin/logout">
              <%=t ( "adminMenu.str11") %>
            </a>
          </div>
        </li>
      </ul>
    </li>
  </ul>
</div>

app/views/view_admin/elements/_menu.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag("Admin/img/user2-160x160.jpg", :alt => "User Image") %>
      </div>
      <div class="pull-left info">
        <p><%= t("adminMenu.str1") %>
        </p>
        <!-- Status -->
        <a href="#">
          <i class="fa fa-circle text-success">
          </i> <%= t("adminMenu.str2") %>
        </a>
      </div>
    </div>

    <ul class="sidebar-menu">
      <li class="header"><%= t("adminMenu.str3") %>
      </li>
      <li>
        <a href="/admin">
          <i class="fa fa-bar-chart">
          </i>
          <span><%= t("adminMenu.str4") %>
          </span>
        </a>
      </li>
      <li>
        <a href="/admin">
          <i class="fa fa-thumbs-up">
          </i>
          <span><%= t("adminMenu.str5") %>
          </span>
        </a>
      </li>
      <li>
        <a href= <%= categories_path %> >
          <i class="fa fa-comments-o">
          </i>
          <span><%= t("adminMenu.str6") %>
          </span>
        </a>
      </li> 
       <li>
        <a href= <%= small_categories_path  %> >
          <i class="fa fa-comments-o">
          </i>
          <span><%= t("adminMenu.str12") %>
          </span>
        </a>
      </li>
      <li>
        <a href="/admin">
          <i class="fa fa-user-secret">
          </i>
          <span><%= t("adminMenu.str7") %>
          </span>
        </a>
      </li>
      <li>
        <a href="/admin">
          <i class="fa fa-fax">
          </i>
          <span><%= t("adminMenu.str8") %>
          </span>
        </a>
      </li>
      <li>
        <a href="/admin">
          <i class="fa fa-fax">
          </i>
          <span><%= t("adminMenu.str9") %>
          </span>
        </a>
      </li>
    </ul>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/view_admin/home.html.erb
<% provide(:title, t( ".title")) %>
  <div class="wrapper">
    <header class="main-header">
      <a href="/test/public/" class="logo">
        <span class="logo-mini"><b><%= t("adminHome.str1") %></b></span>
        <span class="logo-lg">
          <%= image_tag("Admin/img/scart-min.png", :alt => "img") %>
        </span>
      </a>
      <nav class="navbar navbar-static-top" role="navigation">
        <%=render "view_admin/elements/NavbarRightMenu" %>
      </nav>
    </header>
    <%=render "view_admin/elements/menu" %>
      <div class="content-wrapper" id="pjax-container">
        <section class="content-header">
          <h1> <%= t("adminHome.str2") %>
            <small> </small>
          </h1>
        </section>
        <section class="content">
          <div class="row">
            <div class="col-md-4">
              <div class="small-box bg-aqua">
                <div class="inner">
                  <h3>26</h3>
                  <p><%= t("adminHome.str3") %></p>
                </div>
                <div class="icon">
                  <i class="fa fa-tags"></i>
                </div>
                <a href="/admin" class="small-box-footer">
                  <%= t("adminHome.str6") %>&nbsp;
                  <i class="fa fa-arrow-circle-right"></i>
                </a>
              </div>
            </div>
            <div class="col-md-4">
              <div class="small-box bg-green">
                <div class="inner">
                  <h3>102</h3>
                  <p><%= t("adminHome.str4") %></p>
                </div>
                <div class="icon">
                  <i class="fa fa-group"></i>
                </div>
                <a href="/admin" class="small-box-footer">
                  <%= t("adminHome.str6") %>&nbsp;
                  <i class="fa fa-arrow-circle-right"></i>
                </a>
              </div>
            </div>
            <div class="col-md-4">
              <div class="small-box bg-yellow">
                <div class="inner">
                  <h3>201</h3>
                  <p><%= t("adminHome.str5") %></p>
                </div>
                <div class="icon">
                  <i class="fa fa-user"></i>
                </div>
                <a href="/admin" class="small-box-footer">
                  <%= t("adminHome.str6") %>&nbsp;
                  <i class="fa fa-arrow-circle-right"></i>
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

  </div>