config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  get "users/new"
  root "view_web#home"

  get "/admin", to: "view_admin#home"
  get "view_web/home", to: "view_web#home"
  get "view_web/about", to: "view_web#about"
  get "view_web/contacts", to: "view_web#contacts"
  get "view_web/product", to: "view_web#product"
  get "view_web/collections", to: "view_web#collections"
  get "view_web/account/register", to: "users#new"
  post "view_web/account/register",  to: "users#create"
  get "view_web/account", to: "view_web#account"
  get "view_web/cart", to: "view_web#cart"
  get "view_web/account/login", to: "sessions#new"
  post "view_web/account/login",  to: "sessions#create"
  delete "view_web/account/logout",  to: "sessions#destroy"
  resources :users


  resources :categories
  resources :small_categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :small_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  has_many :order_details
end

app/models/image_product.rb
class ImageProduct < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
  enum status: { put: 0, wait: 1, approved: 2, sent: 3 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :history
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :small_category
  has_many :image_products
  enum status: { stocking: 0, outofstock: 1 }
end

app/models/rank.rb
class Rank < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/slide.rb
class Slide < ApplicationRecord
end

app/models/small_category.rb
class SmallCategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


  has_many :contacts
  has_many :ranks
  has_many :comments
  has_one :history
  has_many :orders
  enum role: { admin: 0, member: 1 }

  has_secure_password

  validates :address, presence: true,
    length: {maximum: Settings.user.address_max_length}
  validates :email, presence: true, length: {maximum: Settings.user.email_length},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :name, presence: true, length: {maximum: Settings.user.name_length}
  validates :password, presence: true,
    length: {minimum: Settings.user.pass_length}, allow_nil: true
  validates :phone, presence: true,
    length: {maximum: Settings.user.phone_number_length}

  before_save ->{email.downcase!}

  def self.digest string
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, except: [:new, :index, :create]
  def index
  	@categories = Category.all
  end
  def edit
    
  end
  def new
  	@category = Category.new
  end
  def create
    @category = Category.new category_params
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = t "updated"
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "category_deleted"
      redirect_to categories_path
    else
      flash[:danger] = t "category_not_found"
      redirect_to categories_path
    end
  end


  private

    def category_params
      params.require(:category).permit(:name, :description)
    end

    def load_category
      @category = Category.find_by id: params[:id] 
      return if @category

      flash[:danger] = t "category_not_found"
      redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = t "errors.msg1"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = t("welcome")
      redirect_to root_url
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :phone, :address,
       :password, :password_confirmation)
    end
end

app/controllers/view_web_controller.rb
class ViewWebController < ApplicationController
  def home
    @products = Product.joins("INNER JOIN ranks ON product_id = products.id").limit(12).order("star_level desc")
  end

  def about
  end

  def contacts
  end

  def product
  end

  def collections
  end

  def login
  end

  def account
  end

  def cart
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = I18n.t ".base_title"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in user
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete:user_id
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/view_admin_helper.rb
module ViewAdminHelper
end

app/helpers/view_web_helper.rb
module ViewWebHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <input type="hidden" name="_token" value="{{ csrf_token() }}">
  <div class="box-body">
  	<div class="fields-group">
    	<div class="form-group  ">
    		<%= f.label :name, t(".namecategory") %>
    		<%= f.text_field :name, class: "form-control" %>
    	</div>
    	<div class="form-group  ">
    		<%= f.label :description, t(".description") %>
		    <%= f.text_field :description, class: "form-control" %>
		  </div>
    </div>
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
    <input type="hidden" name="_token" value="YkDCfkRWPRyZTW2zQVo3IfKy3x6paUJmuFe7BBwx">
    <div class="col-md-2"> </div>
    <div class="col-md-8">
      <div class="btn-group pull-right">
        <%= f.submit t(".submit"), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <input type="hidden" name="_previous_" value="" class="_previous_" />
  <!-- /.box-footer -->
<% end %>

app/views/categories/edit.html.erb
<% provide(:title, t( ".title")) %>
  <div class="wrapper">
    <header class="main-header">
      <a href="/test/public/" class="logo">
        <span class="logo-mini"><b><%= t("adminHome.str1") %></b></span>
        <span class="logo-lg">
          <%= image_tag("Admin/img/scart-min.png", :alt => "img") %>
        </span>
      </a>
      <nav class="navbar navbar-static-top" role="navigation">
        <%=render "view_admin/elements/NavbarRightMenu" %>
      </nav>
    </header>
    <%=render "view_admin/elements/menu" %>
    <div class="content-wrapper" id="pjax-container">
      <section class="content-header">
        <h1><%= t ".str1" %></h1>
        <!-- breadcrumb start -->
        <!-- breadcrumb end -->
      </section>
      <section class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="box box-info">
              <div class="box-header with-border">
                <h3 class="box-title"><%= t ".str2" %></h3>
                <div class="box-tools">
                  <div class="btn-group pull-right" style="margin-right: 5px"> <a href= <%= categories_path %> class="btn btn-sm btn-default" title="List"><i class="fa fa-list"></i><span class="hidden-xs">&nbsp;<%= t ".list" %></span></a> </div>
                </div>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%=render "categories/form" %>
            </div>
          </div>
        </div>
      </section>
      <%= javascript_include_tag "edit" %>
    </div>
  </div>

app/views/categories/index.html.erb
<% provide(:title, t( ".title")) %>
  <div class="wrapper">
    <header class="main-header">
      <a href="/test/public/" class="logo">
        <span class="logo-mini"><b><%= t("adminHome.str1") %></b></span>
        <span class="logo-lg">
          <%= image_tag("Admin/img/scart-min.png", :alt => "img") %>
        </span>
      </a>
      <nav class="navbar navbar-static-top" role="navigation">
        <%=render "view_admin/elements/NavbarRightMenu" %>
      </nav>
    </header>
    <%=render "view_admin/elements/menu" %>
    <div class="content-wrapper" id="pjax-container">
      <section class="content-header">
        <h1><%= t ".str1"%></h1>
        <!-- breadcrumb start -->
        <!-- breadcrumb end -->
      </section>
      <section class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="box">
              <div class="box-header with-border">
                <div class="pull-right">
                  <div class="btn-group pull-right" style="margin-right: 10px">
                    <a href= <%= new_category_path %> class="btn btn-sm btn-success" title="New"> <i class="fa fa-save"></i><span class="hidden-xs">&nbsp;&nbsp;<%= t ".new" %></span> </a>
                  </div>
                </div> 
              </div>
              <!-- /.box-header -->
              <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th><%= t ".id" %></th>
                      <th><%= t ".namecategory" %></th>
                      <th><%= t ".description" %></th>
                      <th><%= t ".action" %></th>
                    </tr>
                  </thead>
                  <tbody> 
                    <% @categories.each do |category| %>
                      <tr>
                        <td><%= category.id %></td>
                        <td><%= category.name %></td>
                        <td><%= category.description %></td>
                        <td>
                          <a title="Show Customer detail" href= <%= edit_category_path(category) %> > 
                            <i class="fa fa-edit"></i> 
                          </a>
                          <a href= <%= category_path(category)%> data-method = "delete" data-confirm = "Bạn có chắc chắn xóa?" >                       
                            <i class="fa fa-trash"> </i>                           
                          </a>
                        </td>
                      </tr> 
                    <% end %>
                  </tbody>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>

app/views/categories/new.html.erb
<% provide(:title, t( ".title")) %>
  <div class="wrapper">
    <header class="main-header">
      <a href="/test/public/" class="logo">
        <span class="logo-mini"><b><%= t("adminHome.str1") %></b></span>
        <span class="logo-lg">
          <%= image_tag("Admin/img/scart-min.png", :alt => "img") %>
        </span>
      </a>
      <nav class="navbar navbar-static-top" role="navigation">
        <%=render "view_admin/elements/NavbarRightMenu" %>
      </nav>
    </header>
    <%=render "view_admin/elements/menu" %>
    <div class="content-wrapper" id="pjax-container">
      <section class="content-header">
        <h1><%= t ".str1" %></h1>
        <!-- breadcrumb start -->
        <!-- breadcrumb end -->
      </section>
      <section class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="box box-info">
              <div class="box-header with-border">
                <h3 class="box-title"><%= t ".str2" %></h3>
                <div class="box-tools">
                  <div class="btn-group pull-right" style="margin-right: 5px"> <a href= <%= categories_path %> class="btn btn-sm btn-default" title="List"><i class="fa fa-list"></i><span class="hidden-xs">&nbsp;<%= t ".list" %></span></a> </div>
                </div>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%=render "categories/form" %>
            </div>
          </div>
        </div>
      </section>
      <%= javascript_include_tag "new" %>
    </div>
  </div>

app/views/view_web/elements/_chat.html.erb
<div id="fb-root">
  <%= stylesheet_link_tag "chat" %>
  <%= javascript_include_tag "chat" %>
  <div id="cfacebook">
    <a href="javascript:;" class="chat_fb" onclick="return:false;">
      <i class="fa fa-facebook-square"></i> <%= t("chat.str1") %>
    </a>
    <div class="fchat">
      <div class="fb-page" data-tabs="messages" data-href="https://www.facebook.com/FAshopdanang/"
      data-width="250" data-height="400" data-small-header="false" data-adapt-container-width="true"
      data-hide-cover="false" data-show-facepile="true" data-show-posts="false">
      </div>
    </div>
  </div>
</div>

app/views/view_web/elements/_header-wrapper.html.erb
<div class="header-wrapper">
  <header id="header" class="header-design8">
    <div class="container">
      <div class="row">
        <div class="col-sm-4 col-md-4 col-lg-4 col-xl-5">
          <a href="/"><img class="logo img-responsive" src="//cdn.shopify.com/s/files/1/1637/5229/t/4/assets/logo.png?0" alt="logo" /> </a>
        </div>
        <div class="col-sm-8 col-md-8 col-lg-8 col-xl-7 text-right">
          <div class="settings">
            <div class="account-row-list mobile-menu-off" style="display: inline-block;">
              <ul>
                <% if logged_in? %>
                  <li><%= link_to "Users", '#' %></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <%= t("header-wrapper.str1") %> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", '#' %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Log out", view_web_account_logout_path, method: :delete %>
                      </li>
                    </ul>
                  </li>
                <% else %>
                  <li>
                    <a>
                      <span class="icon icon-lock"></span>
                      <%= link_to t("header-wrapper.str3"), view_web_account_login_path %>
                    </a>
                  </li>
                <% end %>
                <li><a href="/view_web/account/register"><span class="icon icon-person_add"></span><%= t("header-wrapper.str4") %></a> </li>

              </ul>
            </div>
            <!-- shopping cart start -->
            <div class="cart link-inline header-cart mobile-menu-off">
              <div class="dropdown text-right">
                <a class="dropdown-toggle"> <span class="icon icon-shopping_basket"></span> <span class="badge badge--cart bigcounter">1</span> </a>
                <div class="dropdown-menu dropdown-menu--xs-full slide-from-top cart-group-1"
                role="menu">
                  <div class="container">
                    <div class="cart__top"><%= t("header-wrapper.str8") %></div> <a href="#" class="icon icon-close cart__close"><span><%= t("header-wrapper.str5") %></span></a>
                    <ul>
                      <li class="cart__item">
                        <div class="cart__item__image pull-left">
                          <a href="/products/paul-smith-blazer?variant=31530899532"><img src="//cdn.shopify.com/s/files/1/1637/5229/products/LEATHER_FUR_CROSSBODY_BAG_4_small.jpg?v=1481124090" alt="" /> </a>
                        </div>
                        <div class="cart__item__control">
                          <div class="cart__item__delete"><a href="javascript:void(0);" onclick="Shopify.removeItem(31530899532)" class="icon icon-delete"><span><%= t("header-wrapper.str9") %></span></a> </div>
                          <div class="cart__item__edit"><a href="/products/paul-smith-blazer?variant=31530899532" class="icon icon-edit"><span><%= t("header-wrapper.str10") %></span></a> </div>
                        </div>
                        <div class="cart__item__info">
                          <div class="cart__item__info__title">
                            <h2 class="title-center"><a href="/products/paul-smith-blazer?variant=31530899532">D-Kallien Boots - S / green</a></h2> </div>
                          <div class="cart__item__info__price"><span class="info-label"><%= t("header-wrapper.str12") %></span><span><span class=money>$85.00</span></span>
                          </div>
                          <div class="cart__item__info__price" style="right: 35%;"><span class="info-label"><%= t("header-wrapper.str11") %></span><span>1</span> </div>
                        </div>
                      </li>
                    </ul>
                    <div class="cart__bottom"> <a href="/checkout" class="btn btn--ys btn-checkout"><%= t("header-wrapper.str13") %> <span class="icon icon--flippedX icon-reply"></span></a>
                      <div class="cart__total"><%= t("header-wrapper.str14") %><span class="shopping-cart__total"> <span class=money>$85.00</span></span>
                      </div> <a href="/view_web/cart" class="btn btn--ys"><span class="icon icon-shopping_basket"></span><%= t("header-wrapper.str15") %></a> </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- shopping cart end -->
          </div>
        </div>
      </div>
    </div>
    <div class="container showscreen1024">
      <div class="row text-center">
        <div class="text-right extra-right">
          <!-- account menu start -->
          <div class="account link-inline ">
            <div class="dropdown text-right">
              <a class="dropdown-toggle" data-toggle="dropdown"> <span class="icon icon-person "></span> </a>
              <ul class="dropdown-menu dropdown-menu--xs-full">
                <li><a href="/view_web/account"><span class="icon icon-person"></span><%= t("header-wrapper.str1") %></a> </li>
                <li><a href="/view_web/checkout"><span class="icon icon-done_all"></span><%= t("header-wrapper.str2") %></a> </li>
                <li><a href="/view_web/account/login"><span class="icon icon-lock"></span><%= t("header-wrapper.str3") %></a> </li>
                <li><a href="/view_web/account/register"><span class="icon icon-person_add"></span><%= t("header-wrapper.str4") %></a> </li>
                <li class="dropdown-menu__close"><a href="#"><span class="icon icon-close"></span><%= t("header-wrapper.str5") %></a> </li>
              </ul>
            </div>
          </div>
          <!-- account menu end -->
        </div>
      </div>
    </div>
    <div class="stuck-nav">
      <div class="container offset-top-5">
        <div class="row">
          <div class="pull-left col-sm-10 col-md-10 col-lg-10">
            <nav class="navbar ">
              <div class="responsive-menu mainMenu">
                <div class="col-xs-2 visible-mobile-menu-on">
                  <div class="expand-nav compact-hidden">
                    <a href="#off-canvas-menu" id="off-canvas-menu-toggle">
                      <div class="navbar-toggle"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="menu-text"><%= t("header-wrapper.str6") %></span> </div>
                    </a>
                  </div>
                </div>
                <ul class="nav navbar-nav">
                  <li class="dl-close"></li>
                  <li class="dropdown dropdown-mega-menu dropdown-one-col">
                    <a href="/" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="act-underline"><%= t("header-wrapper.str16") %></span>
                    </a>
                  </li>
                  <li class="dropdown dropdown-mega-menu">
                    <a href="/view_web/collections" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="act-underline"><%= t("header-wrapper.str17") %></span>
                    </a>
                  </li>
                  <li class="dropdown dropdown-mega-menu dropdown-two-col">
                    <a href="/view_web/about" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="act-underline"><%= t("header-wrapper.str18") %></span>
                    </a>
                  </li>
                  <li class="dropdown dropdown-mega-menu dropdown-one-col">
                    <a href="/view_web/contacts" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="act-underline"><%= t("header-wrapper.str7") %></span>
                    </a>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
          <div class="pull-right col-sm-2 col-md-2 col-lg-2">
            <div class="text-right">
              <!-- search start -->
              <div class="search link-inline "> <a href="#" class="search__open"><span class="icon icon-search"></span></a>
                <div class="search-dropdown">
                  <form action="/search" method="get">
                    <div class="input-outer">
                      <input type="hidden" name="type" value="product" />
                      <input type="text" name="q" class="search_field" value="" maxlength="128" placeholder="SEARCH:">
                      <button type="submit" title="" class="icon icon-search"></button>
                    </div> <a href="#" class="search__close"><span class="icon icon-close"></span></a> </form>
                </div>
              </div>
              <!-- search end -->
              <!-- shopping cart start -->
              <div class="cart link-inline header-cart">
                <div class="dropdown text-right">
                  <a class="dropdown-toggle"> <span class="icon icon-shopping_basket"></span> <span class="badge badge--cart bigcounter">1</span> </a>
                  <div class="dropdown-menu dropdown-menu--xs-full slide-from-top cart-group-1"
                  role="menu">
                    <div class="container">
                      <div class="cart__top"><%= t("header-wrapper.str8") %></div> <a href="#" class="icon icon-close cart__close"><span><%= t("header-wrapper.str5") %></span></a>
                      <ul>
                        <li class="cart__item">
                          <div class="cart__item__image pull-left">
                            <a href="/products/paul-smith-blazer?variant=31530899532"><img src="//cdn.shopify.com/s/files/1/1637/5229/products/LEATHER_FUR_CROSSBODY_BAG_4_small.jpg?v=1481124090" alt="" /> </a>
                          </div>
                          <div class="cart__item__control">
                            <div class="cart__item__delete"><a href="javascript:void(0);" onclick="Shopify.removeItem(31530899532)" class="icon icon-delete"><span><%= t("header-wrapper.str9") %></span></a> </div>
                            <div
                            class="cart__item__edit"><a href="/products/paul-smith-blazer?variant=31530899532" class="icon icon-edit"><span><%= t("header-wrapper.str10") %></span></a>
                          </div>
                    </div>
                    <div class="cart__item__info">
                      <div class="cart__item__info__title">
                        <h2 class="title-center"><a href="/products/paul-smith-blazer?variant=31530899532">D-Kallien Boots - S / green</a></h2> </div>
                      <div class="cart__item__info__price"><span class="info-label"><%= t("header-wrapper.str12") %></span><span><span class=money>$85.00</span></span>
                      </div>
                      <div class="cart__item__info__price" style="right: 35%;"><span class="info-label"><%= t("header-wrapper.str11") %></span><span>1</span> </div>
                    </div>
                    </li>
                    </ul>
                    <div class="cart__bottom"> <a href="/checkout" class="btn btn--ys btn-checkout"><%= t("header-wrapper.str13") %> <span class="icon icon--flippedX icon-reply"></span></a>
                      <div class="cart__total"><%= t("header-wrapper.str14") %><span class="shopping-cart__total"> <span class=money>$85.00</span></span>
                      </div> <a href="/cart" class="btn btn--ys"><span class="icon icon-shopping_basket"></span><%= t("header-wrapper.str15") %></a> </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- shopping cart end -->
          </div>
        </div>
      </div>
    </div>
  </header>
</div>